services:
  php-app:
    build:
      context: .
    container_name: php-app
    restart: unless-stopped
    init: true
    working_dir: /var/www/html
    # env_file: ./.env  # Uncomment if .env file exists
    depends_on:
      - mysql-db
    networks:
      - backend
    expose:
      - "9000"  # php-fpm default port
    # If you want to serve via web server (nginx/apache), add a web service and link to this one

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this in production
      MYSQL_DATABASE: notes_db
      MYSQL_USER: notes_user
      MYSQL_PASSWORD: notes_password  # Change this in production
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"  # Expose MySQL for local development

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  # Persistent storage for MySQL
